
CREATE TABLE profile
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT       NOT NULL UNIQUE,
    slug                   VARCHAR(30)  NOT NULL UNIQUE,
    nickname               VARCHAR(20)  NOT NULL,
    bio                    VARCHAR(80),
    avatar_url             VARCHAR(1000),
    background_url         VARCHAR(1000),
    background_color       VARCHAR(20),
    font_color             VARCHAR(20),
    link_layout            VARCHAR(20)  NOT NULL DEFAULT 'list',
    link_style             VARCHAR(20)  NOT NULL DEFAULT 'fill',
    link_round             VARCHAR(10)  NOT NULL DEFAULT 'sm',
    font_family            VARCHAR(30)  NOT NULL DEFAULT 'pretendard',
    header_layout          VARCHAR(20)  NOT NULL DEFAULT 'center',
    link_animation         VARCHAR(20)  NOT NULL DEFAULT 'none',
    color_theme            VARCHAR(20)  NOT NULL DEFAULT 'default',
    custom_primary_color   VARCHAR(20),
    custom_secondary_color VARCHAR(20),
    dark_mode              BOOLEAN      NOT NULL DEFAULT FALSE,
    background_texture     VARCHAR(20),
    decorator1_type        VARCHAR(20),
    decorator1_text        VARCHAR(80),
    decorator2_type        VARCHAR(20),
    decorator2_text        VARCHAR(80),
    link_gradient_from     VARCHAR(20),
    link_gradient_to       VARCHAR(20),
    link_border_color      VARCHAR(20),
    link_border_thick      VARCHAR(20)  NOT NULL DEFAULT 'thin',
    page_layout            VARCHAR(20)  NOT NULL DEFAULT 'list',
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by             BIGINT       NOT NULL DEFAULT 0,
    updated_by             BIGINT       NOT NULL DEFAULT 0,
    is_deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at             TIMESTAMPTZ,

    CONSTRAINT fk_profile_users
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE  profile                    IS '프로필 마스터';
COMMENT ON COLUMN profile.user_id            IS '사용자 FK';
COMMENT ON COLUMN profile.slug               IS '공개 URL slug (3~30자)';
COMMENT ON COLUMN profile.nickname           IS '닉네임 (2~20자)';
COMMENT ON COLUMN profile.bio               IS '자기소개 (최대 80자)';
COMMENT ON COLUMN profile.font_color         IS '폰트 색상 (hex)';
COMMENT ON COLUMN profile.link_layout        IS '링크 레이아웃 (list, grid-2, grid-3)';
COMMENT ON COLUMN profile.link_style         IS '링크 스타일 (fill, outline, shadow, rounded, pill)';
COMMENT ON COLUMN profile.link_round         IS '링크 모서리 반경 (sm, md, lg, full)';
COMMENT ON COLUMN profile.background_texture IS '배경 텍스처';
COMMENT ON COLUMN profile.link_border_thick  IS '링크 테두리 굵기 (thin, medium, thick)';
COMMENT ON COLUMN profile.page_layout        IS '페이지 레이아웃';

CREATE INDEX idx_profile_user_id ON profile (user_id);
CREATE INDEX idx_profile_slug    ON profile (slug);

CREATE TABLE profile_link
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id     BIGINT        NOT NULL,
    title          VARCHAR(100)  NOT NULL,
    url            VARCHAR(1000) NOT NULL,
    image_url      VARCHAR(1000),
    description    VARCHAR(200),
    sort_order     INT           NOT NULL DEFAULT 0,
    enabled        BOOLEAN       NOT NULL DEFAULT TRUE,
    price          BIGINT,
    original_price BIGINT,
    discount_rate  INTEGER,
    store          VARCHAR(50),
    category       VARCHAR(50),
    clicks         BIGINT        NOT NULL DEFAULT 0,
    likes          BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     BIGINT        NOT NULL DEFAULT 0,
    updated_by     BIGINT        NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,

    CONSTRAINT fk_profile_link_profile
        FOREIGN KEY (profile_id) REFERENCES profile (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE  profile_link               IS '프로필 링크';
COMMENT ON COLUMN profile_link.profile_id    IS '프로필 FK';
COMMENT ON COLUMN profile_link.title         IS '링크 제목 (최대 100자)';
COMMENT ON COLUMN profile_link.description   IS '링크 설명 (최대 200자)';
COMMENT ON COLUMN profile_link.sort_order    IS '정렬 순서';
COMMENT ON COLUMN profile_link.price         IS '상품 가격';
COMMENT ON COLUMN profile_link.original_price IS '상품 원가';
COMMENT ON COLUMN profile_link.discount_rate  IS '할인율 (%)';
COMMENT ON COLUMN profile_link.clicks        IS '클릭 수 (비정규화)';
COMMENT ON COLUMN profile_link.likes         IS '좋아요 수 (비정규화)';

CREATE INDEX idx_profile_link_profile_id ON profile_link (profile_id);

CREATE TABLE profile_social
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT        NOT NULL,
    platform   VARCHAR(30)   NOT NULL,
    url        VARCHAR(1000) NOT NULL,
    sort_order INT           NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by BIGINT        NOT NULL DEFAULT 0,
    updated_by BIGINT        NOT NULL DEFAULT 0,
    is_deleted BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_profile_social_profile
        FOREIGN KEY (profile_id) REFERENCES profile (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE  profile_social            IS '프로필 소셜 링크';
COMMENT ON COLUMN profile_social.profile_id IS '프로필 FK';
COMMENT ON COLUMN profile_social.platform   IS '소셜 플랫폼 (instagram, youtube, x 등)';
COMMENT ON COLUMN profile_social.sort_order IS '정렬 순서';

CREATE INDEX idx_profile_social_profile_id ON profile_social (profile_id);
