-- =============================================================
-- V002: 프로필, 프로필 링크, 소셜 링크
-- =============================================================

-- 프로필: 유저당 1개, 테마/레이아웃 설정 포함
CREATE TABLE mst_profile
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT       NOT NULL UNIQUE,
    slug                   VARCHAR(30)  NOT NULL UNIQUE,
    nickname               VARCHAR(20)  NOT NULL,
    bio                    VARCHAR(80),
    avatar_url             VARCHAR(1000),
    background_url         VARCHAR(1000),
    background_color       VARCHAR(20),
    link_layout            VARCHAR(20)  NOT NULL DEFAULT 'list',
    link_style             VARCHAR(20)  NOT NULL DEFAULT 'fill',
    font_family            VARCHAR(30)  NOT NULL DEFAULT 'pretendard',
    header_layout          VARCHAR(20)  NOT NULL DEFAULT 'center',
    link_animation         VARCHAR(20)  NOT NULL DEFAULT 'none',
    color_theme            VARCHAR(20)  NOT NULL DEFAULT 'default',
    custom_primary_color   VARCHAR(20),
    custom_secondary_color VARCHAR(20),
    dark_mode              BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by             BIGINT       NOT NULL DEFAULT 0,
    updated_by             BIGINT       NOT NULL DEFAULT 0,
    is_deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at             TIMESTAMPTZ,

    CONSTRAINT fk_mst_profile_mst_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE mst_profile IS '프로필 마스터';
COMMENT ON COLUMN mst_profile.id IS 'PK';
COMMENT ON COLUMN mst_profile.user_id IS '사용자 FK';
COMMENT ON COLUMN mst_profile.slug IS '공개 URL slug (3~30자)';
COMMENT ON COLUMN mst_profile.nickname IS '닉네임 (2~20자)';
COMMENT ON COLUMN mst_profile.bio IS '자기소개 (최대 80자)';
COMMENT ON COLUMN mst_profile.avatar_url IS '아바타 이미지 URL';
COMMENT ON COLUMN mst_profile.background_url IS '배경 이미지 URL';
COMMENT ON COLUMN mst_profile.background_color IS '배경 색상 (hex)';
COMMENT ON COLUMN mst_profile.link_layout IS '링크 레이아웃 (list, grid-2, grid-3)';
COMMENT ON COLUMN mst_profile.link_style IS '링크 스타일 (fill, outline, shadow, rounded, pill)';
COMMENT ON COLUMN mst_profile.font_family IS '폰트 패밀리';
COMMENT ON COLUMN mst_profile.header_layout IS '헤더 레이아웃 (center, left, avatar-only, banner-only)';
COMMENT ON COLUMN mst_profile.link_animation IS '링크 애니메이션 (none, fade-in, slide-up, scale, stagger)';
COMMENT ON COLUMN mst_profile.color_theme IS '컬러 테마';
COMMENT ON COLUMN mst_profile.dark_mode IS '다크모드 여부';

CREATE INDEX idx_mst_profile_user_id ON mst_profile (user_id);
CREATE INDEX idx_mst_profile_slug ON mst_profile (slug);

-- 프로필 링크: 최대 20개
CREATE TABLE mst_profile_link
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT       NOT NULL,
    title       VARCHAR(100) NOT NULL,
    url         VARCHAR(1000) NOT NULL,
    image_url   VARCHAR(1000),
    description VARCHAR(200),
    sort_order  INT          NOT NULL DEFAULT 0,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  BIGINT       NOT NULL DEFAULT 0,
    updated_by  BIGINT       NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT fk_mst_profile_link_mst_profile
        FOREIGN KEY (profile_id) REFERENCES mst_profile (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE mst_profile_link IS '프로필 링크';
COMMENT ON COLUMN mst_profile_link.id IS 'PK';
COMMENT ON COLUMN mst_profile_link.profile_id IS '프로필 FK';
COMMENT ON COLUMN mst_profile_link.title IS '링크 제목 (최대 100자)';
COMMENT ON COLUMN mst_profile_link.url IS '링크 URL';
COMMENT ON COLUMN mst_profile_link.image_url IS '링크 이미지 URL';
COMMENT ON COLUMN mst_profile_link.description IS '링크 설명 (최대 200자)';
COMMENT ON COLUMN mst_profile_link.sort_order IS '정렬 순서';
COMMENT ON COLUMN mst_profile_link.enabled IS '활성 여부';

CREATE INDEX idx_mst_profile_link_profile_id ON mst_profile_link (profile_id);

-- 소셜 링크: 최대 8개
CREATE TABLE mst_profile_social
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT       NOT NULL,
    platform   VARCHAR(30)  NOT NULL,
    url        VARCHAR(1000) NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by BIGINT       NOT NULL DEFAULT 0,
    updated_by BIGINT       NOT NULL DEFAULT 0,
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_mst_profile_social_mst_profile
        FOREIGN KEY (profile_id) REFERENCES mst_profile (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE mst_profile_social IS '프로필 소셜 링크';
COMMENT ON COLUMN mst_profile_social.id IS 'PK';
COMMENT ON COLUMN mst_profile_social.profile_id IS '프로필 FK';
COMMENT ON COLUMN mst_profile_social.platform IS '소셜 플랫폼 (instagram, youtube, x 등)';
COMMENT ON COLUMN mst_profile_social.url IS '소셜 URL 또는 핸들';
COMMENT ON COLUMN mst_profile_social.sort_order IS '정렬 순서';

CREATE INDEX idx_mst_profile_social_profile_id ON mst_profile_social (profile_id);
