
CREATE TABLE page_view
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT       NOT NULL,
    slug       VARCHAR(30)  NOT NULL,
    ip         VARCHAR(45),
    user_agent VARCHAR(500),
    referer    VARCHAR(1000),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_page_view_profile
        FOREIGN KEY (profile_id) REFERENCES profile (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE page_view IS '프로필 페이지 조회 이력';
COMMENT ON COLUMN page_view.id IS 'PK';
COMMENT ON COLUMN page_view.profile_id IS '프로필 FK';
COMMENT ON COLUMN page_view.slug IS '조회된 slug';
COMMENT ON COLUMN page_view.ip IS '접속 IP';
COMMENT ON COLUMN page_view.user_agent IS '브라우저 User-Agent';
COMMENT ON COLUMN page_view.referer IS 'HTTP Referer';

CREATE INDEX idx_page_view_profile_id ON page_view (profile_id);
CREATE INDEX idx_page_view_slug_created ON page_view (slug, created_at);

CREATE TABLE link_click
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT       NOT NULL,
    link_id    BIGINT       NOT NULL,
    slug       VARCHAR(30)  NOT NULL,
    ip         VARCHAR(45),
    user_agent VARCHAR(500),
    referer    VARCHAR(1000),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_link_click_profile
        FOREIGN KEY (profile_id) REFERENCES profile (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,

    CONSTRAINT fk_link_click_profile_link
        FOREIGN KEY (link_id) REFERENCES profile_link (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE link_click IS '프로필 링크 클릭 이력';
COMMENT ON COLUMN link_click.id IS 'PK';
COMMENT ON COLUMN link_click.profile_id IS '프로필 FK';
COMMENT ON COLUMN link_click.link_id IS '링크 FK';
COMMENT ON COLUMN link_click.slug IS '프로필 slug';
COMMENT ON COLUMN link_click.ip IS '접속 IP';
COMMENT ON COLUMN link_click.user_agent IS '브라우저 User-Agent';
COMMENT ON COLUMN link_click.referer IS 'HTTP Referer';

CREATE INDEX idx_link_click_profile_id ON link_click (profile_id);
CREATE INDEX idx_link_click_link_id ON link_click (link_id);
CREATE INDEX idx_link_click_created ON link_click (created_at);
