-- =============================================================
-- V004: 핫딜 피드 — 딜, 좋아요, 댓글, 종료투표, 신고
-- =============================================================

-- 핫딜 마스터
CREATE TABLE mst_hot_deal
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT        NOT NULL,
    title              VARCHAR(200)  NOT NULL,
    description        VARCHAR(2000),
    url                VARCHAR(1000) NOT NULL,
    image_url          VARCHAR(1000),
    original_price     INT,
    deal_price         INT,
    discount_rate      INT,
    category           VARCHAR(50),
    store              VARCHAR(100),
    like_count         INT           NOT NULL DEFAULT 0,
    comment_count      INT           NOT NULL DEFAULT 0,
    expired_vote_count INT           NOT NULL DEFAULT 0,
    is_expired         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by         BIGINT        NOT NULL DEFAULT 0,
    updated_by         BIGINT        NOT NULL DEFAULT 0,
    is_deleted         BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMPTZ,

    CONSTRAINT fk_mst_hot_deal_mst_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

COMMENT ON TABLE mst_hot_deal IS '핫딜 마스터';
COMMENT ON COLUMN mst_hot_deal.user_id IS '작성자 FK';
COMMENT ON COLUMN mst_hot_deal.title IS '딜 제목';
COMMENT ON COLUMN mst_hot_deal.url IS '딜 원본 URL';
COMMENT ON COLUMN mst_hot_deal.original_price IS '원래 가격';
COMMENT ON COLUMN mst_hot_deal.deal_price IS '할인 가격';
COMMENT ON COLUMN mst_hot_deal.discount_rate IS '할인율 (%)';
COMMENT ON COLUMN mst_hot_deal.category IS '카테고리';
COMMENT ON COLUMN mst_hot_deal.store IS '판매처';
COMMENT ON COLUMN mst_hot_deal.like_count IS '좋아요 수 (비정규화)';
COMMENT ON COLUMN mst_hot_deal.comment_count IS '댓글 수 (비정규화)';
COMMENT ON COLUMN mst_hot_deal.expired_vote_count IS '종료 투표 수 (비정규화)';
COMMENT ON COLUMN mst_hot_deal.is_expired IS '종료 여부';

CREATE INDEX idx_mst_hot_deal_user_id ON mst_hot_deal (user_id);
CREATE INDEX idx_mst_hot_deal_created ON mst_hot_deal (created_at DESC);
CREATE INDEX idx_mst_hot_deal_popular ON mst_hot_deal (like_count DESC, created_at DESC);
CREATE INDEX idx_mst_hot_deal_discount ON mst_hot_deal (discount_rate DESC NULLS LAST, created_at DESC);

-- 좋아요
CREATE TABLE his_hot_deal_like
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id    BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_his_hot_deal_like_deal
        FOREIGN KEY (deal_id) REFERENCES mst_hot_deal (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_his_hot_deal_like_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT uq_hot_deal_like UNIQUE (deal_id, user_id)
);

COMMENT ON TABLE his_hot_deal_like IS '핫딜 좋아요 이력';

CREATE INDEX idx_his_hot_deal_like_deal ON his_hot_deal_like (deal_id);

-- 댓글 (parent_id로 대댓글)
CREATE TABLE mst_hot_deal_comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id    BIGINT        NOT NULL,
    user_id    BIGINT        NOT NULL,
    parent_id  BIGINT,
    content    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by BIGINT        NOT NULL DEFAULT 0,
    updated_by BIGINT        NOT NULL DEFAULT 0,
    is_deleted BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_mst_hot_deal_comment_deal
        FOREIGN KEY (deal_id) REFERENCES mst_hot_deal (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_mst_hot_deal_comment_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_mst_hot_deal_comment_parent
        FOREIGN KEY (parent_id) REFERENCES mst_hot_deal_comment (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE mst_hot_deal_comment IS '핫딜 댓글';
COMMENT ON COLUMN mst_hot_deal_comment.parent_id IS '부모 댓글 FK (대댓글 시)';

CREATE INDEX idx_mst_hot_deal_comment_deal ON mst_hot_deal_comment (deal_id);
CREATE INDEX idx_mst_hot_deal_comment_parent ON mst_hot_deal_comment (parent_id);

-- 종료 투표
CREATE TABLE his_hot_deal_expired_vote
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id    BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_his_expired_vote_deal
        FOREIGN KEY (deal_id) REFERENCES mst_hot_deal (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_his_expired_vote_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT uq_hot_deal_expired_vote UNIQUE (deal_id, user_id)
);

COMMENT ON TABLE his_hot_deal_expired_vote IS '핫딜 종료 투표 이력';

CREATE INDEX idx_his_expired_vote_deal ON his_hot_deal_expired_vote (deal_id);

-- 딜 신고
CREATE TABLE his_hot_deal_report
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    reason     VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_his_hot_deal_report_deal
        FOREIGN KEY (deal_id) REFERENCES mst_hot_deal (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_his_hot_deal_report_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE his_hot_deal_report IS '핫딜 신고 이력';

-- 댓글 신고
CREATE TABLE his_hot_deal_comment_report
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    reason     VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_his_comment_report_comment
        FOREIGN KEY (comment_id) REFERENCES mst_hot_deal_comment (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_his_comment_report_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE his_hot_deal_comment_report IS '핫딜 댓글 신고 이력';
