CREATE TABLE profile_report
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    reason     VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_profile_report_profile
        FOREIGN KEY (profile_id) REFERENCES profile (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_profile_report_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE profile_report IS '프로필 신고 이력';

CREATE INDEX idx_profile_report_profile ON profile_report (profile_id);

CREATE TABLE profile_link_report
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    reason     VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_profile_link_report_link
        FOREIGN KEY (link_id) REFERENCES profile_link (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_profile_link_report_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE profile_link_report IS '프로필 링크 신고 이력';

CREATE INDEX idx_profile_link_report_link ON profile_link_report (link_id);
