ALTER TABLE mst_user ADD COLUMN created_by BIGINT NOT NULL DEFAULT 0;
ALTER TABLE mst_user ADD COLUMN updated_by BIGINT NOT NULL DEFAULT 0;
ALTER TABLE mst_user ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE mst_user ADD COLUMN remark1 VARCHAR(500);
ALTER TABLE mst_user ADD COLUMN remark2 VARCHAR(500);
ALTER TABLE mst_user ADD COLUMN remark3 VARCHAR(500);
