CREATE TABLE hot_deal_click
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id    BIGINT      NOT NULL,
    user_id    BIGINT,
    ip         VARCHAR(45) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_hot_deal_click_deal
        FOREIGN KEY (deal_id) REFERENCES hot_deal (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE hot_deal_click IS '핫딜 클릭 이력';

CREATE INDEX idx_hot_deal_click_deal ON hot_deal_click (deal_id);
CREATE INDEX idx_hot_deal_click_dedup ON hot_deal_click (deal_id, ip, created_at DESC);

ALTER TABLE hot_deal ADD COLUMN click_count INT NOT NULL DEFAULT 0;
