CREATE TABLE hot_deal_comment_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_comment_like_comment
        FOREIGN KEY (comment_id) REFERENCES hot_deal_comment (id),
    CONSTRAINT fk_comment_like_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_comment_like_user
        UNIQUE (comment_id, user_id)
);

CREATE INDEX idx_comment_like_comment ON hot_deal_comment_like (comment_id);

ALTER TABLE hot_deal_comment ADD COLUMN like_count INT NOT NULL DEFAULT 0;
