CREATE TABLE candidate_hot_deal
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL,
    title          VARCHAR(500),
    url            VARCHAR(1000),
    image_url      VARCHAR(1000),
    original_price INT,
    deal_price     INT,
    store          VARCHAR(100),
    category       VARCHAR(50),
    status         VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_candidate_hot_deal_users
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);
