INSERT INTO mst_hot_deal_comment (deal_id, user_id, parent_id, content, created_at, updated_at, created_by, updated_by, is_deleted) VALUES
(5, 1, NULL, '이 가격이면 역대급이네요 바로 질렀습니다', NOW() - INTERVAL '1 hour', NOW(), 1, 1, false),
(5, 1, NULL, 'M4 칩 성능 체감 많이 되나요?', NOW() - INTERVAL '50 minutes', NOW(), 1, 1, false),
(5, 1, NULL, '교육할인 받으면 더 싸질듯', NOW() - INTERVAL '30 minutes', NOW(), 1, 1, false),
(6, 1, NULL, '갤럭시 S25 울트라 카메라 미쳤다던데', NOW() - INTERVAL '4 hours', NOW(), 1, 1, false),
(6, 1, NULL, 'AI 기능 실사용 후기 궁금합니다', NOW() - INTERVAL '3 hours', NOW(), 1, 1, false),
(7, 1, NULL, '에어랩 가격 진짜 안 떨어지는데 이 정도면 사야됨', NOW() - INTERVAL '20 hours', NOW(), 1, 1, false),
(7, 1, NULL, '남자친구 선물로 사줬는데 반응 폭발', NOW() - INTERVAL '18 hours', NOW(), 1, 1, false),
(7, 1, NULL, '공홈 한정 컬러 예쁘더라고요', NOW() - INTERVAL '15 hours', NOW(), 1, 1, false),
(8, 1, NULL, '나이키 멤버 할인 중복 적용되나요?', NOW() - INTERVAL '2 hours', NOW(), 1, 1, false),
(8, 1, NULL, '실착감 어떤가요? 발볼 넓은편?', NOW() - INTERVAL '1 hour 30 minutes', NOW(), 1, 1, false),
(9, 1, NULL, '한우 등심 이 가격이면 ㄹㅇ 개이득', NOW() - INTERVAL '5 hours', NOW(), 1, 1, false),
(9, 1, NULL, '새벽배송으로 받았는데 신선하네요', NOW() - INTERVAL '4 hours', NOW(), 1, 1, false),
(9, 1, NULL, '마블링 사진 올려주실분?', NOW() - INTERVAL '3 hours', NOW(), 1, 1, false),
(9, 1, NULL, '가족 모임용으로 2팩 샀습니다', NOW() - INTERVAL '2 hours', NOW(), 1, 1, false),
(10, 1, NULL, '에어팟 프로 3 노캔 성능이 2보다 확 좋아졌다던데', NOW() - INTERVAL '7 hours', NOW(), 1, 1, false),
(10, 1, NULL, 'USB-C라 아이폰15 케이블 같이 쓸 수 있어서 편함', NOW() - INTERVAL '6 hours', NOW(), 1, 1, false),
(11, 1, NULL, '스벅 기프트카드 카카오페이 할인 중복 맞나요?', NOW() - INTERVAL '11 hours', NOW(), 1, 1, false),
(11, 1, NULL, '선물용으로 딱이네', NOW() - INTERVAL '10 hours', NOW(), 1, 1, false),
(11, 1, NULL, '매번 이 정도 할인하나요?', NOW() - INTERVAL '9 hours', NOW(), 1, 1, false),
(12, 1, NULL, '무신사 패딩 핏 어떤가요?', NOW() - INTERVAL '1 day 2 hours', NOW(), 1, 1, false),
(12, 1, NULL, '175/70 기준 M 사이즈 적당합니다', NOW() - INTERVAL '1 day 1 hour', NOW(), 1, 1, false),
(12, 1, NULL, '작년 모델이랑 뭐가 다른건지', NOW() - INTERVAL '23 hours', NOW(), 1, 1, false),
(13, 1, NULL, 'LG 그램 무게가 진짜 가볍긴 함', NOW() - INTERVAL '3 hours 30 minutes', NOW(), 1, 1, false),
(13, 1, NULL, '배터리 실사용 몇시간인가요?', NOW() - INTERVAL '3 hours', NOW(), 1, 1, false),
(14, 1, NULL, '제주항공 19900원 아직 남아있나요?', NOW() - INTERVAL '25 minutes', NOW(), 1, 1, false),
(14, 1, NULL, '선착순이라 빨리 예약해야됨 작년에 1시간만에 매진', NOW() - INTERVAL '20 minutes', NOW(), 1, 1, false),
(14, 1, NULL, '수하물 추가하면 결국 비슷한 가격 아닌가', NOW() - INTERVAL '15 minutes', NOW(), 1, 1, false),
(14, 1, NULL, '기내수하물만 가져가면 진짜 2만원', NOW() - INTERVAL '10 minutes', NOW(), 1, 1, false),
(14, 1, NULL, '4월 평일로 예약 성공했습니다!', NOW() - INTERVAL '5 minutes', NOW(), 1, 1, false),
(15, 1, NULL, '올영세일 언제까지인가요?', NOW() - INTERVAL '1 day 20 hours', NOW(), 1, 1, false),
(15, 1, NULL, '이니스프리 그린티 세트 쓸만한가요?', NOW() - INTERVAL '1 day 18 hours', NOW(), 1, 1, false),
(16, 1, NULL, 'MX Master 최고의 마우스 인정', NOW() - INTERVAL '1 day 5 hours', NOW(), 1, 1, false),
(16, 1, NULL, '맥에서도 잘 되나요?', NOW() - INTERVAL '1 day 4 hours', NOW(), 1, 1, false),
(17, 1, NULL, '교보문고 3+1 온라인만 되는건지?', NOW() - INTERVAL '4 hours 30 minutes', NOW(), 1, 1, false),
(17, 1, NULL, '추천 도서 알려주세요!', NOW() - INTERVAL '4 hours', NOW(), 1, 1, false),
(17, 1, NULL, '전자책도 해당되나요?', NOW() - INTERVAL '3 hours 30 minutes', NOW(), 1, 1, false),
(18, 1, NULL, '배민 신규가입 쿠폰 기존 회원은 안되죠?', NOW() - INTERVAL '10 minutes', NOW(), 1, 1, false),
(18, 1, NULL, '새 번호로 가입하면 되긴 함', NOW() - INTERVAL '8 minutes', NOW(), 1, 1, false),
(18, 1, NULL, '무료배달 최소 주문금액 얼마인가요?', NOW() - INTERVAL '5 minutes', NOW(), 1, 1, false),
(19, 1, NULL, '울트라부스트 런닝용으로 어때요?', NOW() - INTERVAL '6 hours 30 minutes', NOW(), 1, 1, false),
(19, 1, NULL, '아디클럽 가입하면 바로 20% 적용되나요?', NOW() - INTERVAL '6 hours', NOW(), 1, 1, false),
(20, 1, NULL, '쿠팡플레이 연간 결제가 확실히 이득', NOW() - INTERVAL '9 hours 30 minutes', NOW(), 1, 1, false),
(20, 1, NULL, '콘텐츠 볼만한거 뭐 있나요?', NOW() - INTERVAL '9 hours', NOW(), 1, 1, false),
(20, 1, NULL, 'SNL 코리아 보려고 가입함', NOW() - INTERVAL '8 hours', NOW(), 1, 1, false),
(25, 1, NULL, '마켓컬리 새벽배송 진짜 빠르긴 함', NOW() - INTERVAL '40 minutes', NOW(), 1, 1, false),
(25, 1, NULL, '5천원 할인이면 거의 공짜네', NOW() - INTERVAL '35 minutes', NOW(), 1, 1, false),
(26, 1, NULL, '49인치 모니터 책상에 들어갈까...', NOW() - INTERVAL '13 hours 30 minutes', NOW(), 1, 1, false),
(28, 1, NULL, '네이버플러스 100원이면 무조건 해야지', NOW() - INTERVAL '15 minutes', NOW(), 1, 1, false),
(28, 1, NULL, '포인트 적립 체감 좋나요?', NOW() - INTERVAL '12 minutes', NOW(), 1, 1, false),
(28, 1, NULL, '첫 달 이후 해지하면 되나요?', NOW() - INTERVAL '10 minutes', NOW(), 1, 1, false),
(29, 1, NULL, '다이소 만원에 10종 가성비 미쳤다', NOW() - INTERVAL '5 hours 30 minutes', NOW(), 1, 1, false),
(29, 1, NULL, '매장마다 세트 구성이 다른가요?', NOW() - INTERVAL '5 hours', NOW(), 1, 1, false),
(31, 1, NULL, '토스뱅크 5% 이자 진짜인가요?', NOW() - INTERVAL '1 hour 50 minutes', NOW(), 1, 1, false),
(31, 1, NULL, '매일 1만원씩이면 부담 없네', NOW() - INTERVAL '1 hour 30 minutes', NOW(), 1, 1, false),
(31, 1, NULL, '세금 떼면 실질 이자는 얼마?', NOW() - INTERVAL '1 hour', NOW(), 1, 1, false),
(34, 1, NULL, '스위치 2 예약 아직 가능한가요?', NOW() - INTERVAL '8 minutes', NOW(), 1, 1, false),
(34, 1, NULL, '출시일 언제인지 아시는분?', NOW() - INTERVAL '6 minutes', NOW(), 1, 1, false),
(34, 1, NULL, '기존 스위치 게임 호환되나요?', NOW() - INTERVAL '4 minutes', NOW(), 1, 1, false),
(34, 1, NULL, '파우치 퀄리티 어떤가요?', NOW() - INTERVAL '2 minutes', NOW(), 1, 1, false),
(23, 1, NULL, '곰표 밀맥주 여름에 시원하게 마시면 최고', NOW() - INTERVAL '2 hours 30 minutes', NOW(), 1, 1, false),
(23, 1, NULL, '편의점 가격 생각하면 반값이네', NOW() - INTERVAL '2 hours', NOW(), 1, 1, false),
(52, 1, NULL, '밀리의서재 오디오북이 진짜 좋음', NOW() - INTERVAL '5 hours 30 minutes', NOW(), 1, 1, false),
(52, 1, NULL, '60% 할인이면 안 할 이유가 없다', NOW() - INTERVAL '5 hours', NOW(), 1, 1, false),
(54, 1, NULL, '로켓와우 첫 달 무료 진짜?', NOW() - INTERVAL '4 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '무료배송만으로도 본전 뽑음', NOW() - INTERVAL '3 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡플레이도 포함이면 개이득', NOW() - INTERVAL '2 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '해지 안 하면 자동결제 되니 주의', NOW() - INTERVAL '1 minute', NOW(), 1, 1, false);
