CREATE TABLE mst_admin (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    role       VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_mst_admin_email ON mst_admin (email);

COMMENT ON TABLE mst_admin IS '관리자 계정';
COMMENT ON COLUMN mst_admin.role IS 'SUPER_ADMIN, ADMIN, MODERATOR';

-- 초기 SUPER_ADMIN (비밀번호: admin1234)
INSERT INTO mst_admin (email, password, name, role)
VALUES ('admin@hddc.dev', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '관리자', 'SUPER_ADMIN');
