-- 쿠팡 로켓와우 멤버십 (deal_id=54) 댓글 + 대댓글 100건
-- 댓글 (parent_id = NULL)
INSERT INTO mst_hot_deal_comment (deal_id, user_id, parent_id, content, created_at, updated_at, created_by, updated_by, is_deleted) VALUES
(54, 1, NULL, '로켓와우 첫 달 무료 진짜인가요? 해지 안 하면 자동결제 되나요?', NOW() - INTERVAL '5 hours', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡플레이까지 포함이면 넷플릭스 해지해도 될듯', NOW() - INTERVAL '4 hours 50 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '로켓배송 무료배송 혜택이 제일 큰 것 같아요', NOW() - INTERVAL '4 hours 40 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '이미 와우 회원인데 첫 달 무료 적용 안 되겠죠?', NOW() - INTERVAL '4 hours 30 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '한 달 써보고 괜찮으면 유지하려구요', NOW() - INTERVAL '4 hours 20 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡이츠 배달비 할인도 되나요?', NOW() - INTERVAL '4 hours 10 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '매달 7890원이면 넷플릭스보다 싸네', NOW() - INTERVAL '4 hours', NOW(), 1, 1, false),
(54, 1, NULL, '로켓프레시 새벽배송이 진짜 편해요 강추', NOW() - INTERVAL '3 hours 50 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '가입하고 바로 해지 예약 걸어두면 됩니다', NOW() - INTERVAL '3 hours 40 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '와우 회원 전용 할인 상품도 꽤 있더라구요', NOW() - INTERVAL '3 hours 30 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡플레이에 SNL 코리아 보려고 가입함ㅋㅋ', NOW() - INTERVAL '3 hours 20 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '혼자 사는 사람한테는 로켓와우가 거의 필수', NOW() - INTERVAL '3 hours 10 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '무료체험 기간에 얼마나 아낄 수 있는지 계산해봄', NOW() - INTERVAL '3 hours', NOW(), 1, 1, false),
(54, 1, NULL, '작년에 가입했다가 해지했는데 다시 무료 되나요?', NOW() - INTERVAL '2 hours 50 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '로켓배송 당일배송이 진짜 빠름 오전에 시키면 저녁에 옴', NOW() - INTERVAL '2 hours 40 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡플레이 4K 화질 지원하나요?', NOW() - INTERVAL '2 hours 30 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '가족이랑 같이 쓸 수 있나요? 계정 공유 되나요?', NOW() - INTERVAL '2 hours 20 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '솔직히 배송비만 생각해도 본전 뽑음', NOW() - INTERVAL '2 hours 10 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡 자체브랜드 상품도 할인 되더라', NOW() - INTERVAL '2 hours', NOW(), 1, 1, false),
(54, 1, NULL, '해외직구도 로켓배송 되는거 알고 계셨나요?', NOW() - INTERVAL '1 hour 50 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '첫 달 무료 + 카드 할인까지 받으면 완전 이득', NOW() - INTERVAL '1 hour 40 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '반품도 무료라서 부담없이 주문할 수 있어요', NOW() - INTERVAL '1 hour 30 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡플레이 오리지널 콘텐츠 꽤 괜찮음', NOW() - INTERVAL '1 hour 20 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '와우 멤버십 해지하니까 배송비 아까워서 다시 가입함', NOW() - INTERVAL '1 hour 10 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '식료품 장보기를 쿠팡으로 다 해결하는 중', NOW() - INTERVAL '1 hour', NOW(), 1, 1, false),
(54, 1, NULL, '무료체험만 하고 해지하는 사람도 많던데', NOW() - INTERVAL '50 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '월 7890원이면 하루에 263원... 커피 한 잔보다 싸다', NOW() - INTERVAL '40 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '쿠팡이츠도 와우 혜택 있으면 좋겠다', NOW() - INTERVAL '30 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '새벽배송으로 아침에 신선한 우유 받는 맛이 있음', NOW() - INTERVAL '20 minutes', NOW(), 1, 1, false),
(54, 1, NULL, '이거 보고 바로 가입했습니다 감사합니다!', NOW() - INTERVAL '10 minutes', NOW(), 1, 1, false);
