-- 핫딜 클릭 이력
CREATE TABLE his_hot_deal_click
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id    BIGINT      NOT NULL,
    user_id    BIGINT,
    ip         VARCHAR(45) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_his_hot_deal_click_deal
        FOREIGN KEY (deal_id) REFERENCES mst_hot_deal (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMENT ON TABLE his_hot_deal_click IS '핫딜 클릭 이력';

CREATE INDEX idx_his_hot_deal_click_deal ON his_hot_deal_click (deal_id);
CREATE INDEX idx_his_hot_deal_click_dedup ON his_hot_deal_click (deal_id, ip, created_at DESC);

-- mst_hot_deal에 click_count 컬럼 추가
ALTER TABLE mst_hot_deal ADD COLUMN click_count INT NOT NULL DEFAULT 0;
