-- 댓글 좋아요 테이블
CREATE TABLE his_hot_deal_comment_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_his_comment_like_comment
        FOREIGN KEY (comment_id) REFERENCES mst_hot_deal_comment (id),
    CONSTRAINT fk_his_comment_like_user
        FOREIGN KEY (user_id) REFERENCES mst_user (id),
    CONSTRAINT uq_comment_like_user
        UNIQUE (comment_id, user_id)
);

CREATE INDEX idx_his_comment_like_comment ON his_hot_deal_comment_like (comment_id);

-- 댓글 테이블에 like_count 컬럼 추가
ALTER TABLE mst_hot_deal_comment ADD COLUMN like_count INT NOT NULL DEFAULT 0;
